```{r}
#***************************************************************
#
#  Read in the data
#
#***************************************************************

setwd("../TransplantData/")
uva <- read.table("UVAxplant.csv", sep = ",", header = T)

mcv <- read.table("MCVxplant.csv", sep = ",", header = T)

duke <- read.table("Dukexplant.csv", sep = ",", header = T)

unc <- read.table("UNCxplant.csv", sep = ",", header = T)

uvaeth <- read.table("UVAethnic.csv", sep = ",", header =T)

mcveth <- read.table("MCVethnic.csv", sep = ",", header =T)

dukeeth <- read.table("DukeEthnic.csv", sep = ",", header =T)

r11donor<-read.table("R11donor.csv", sep = ",", header = T)


#***************************************************************
#
#  Source files and libraries
#
#***************************************************************

# Source 
#setwd(sourcedir)
setwd("../../RCode/")
source("TSbootfunctions.R") # Get the new version of this.
source("Transplant.plots.R")
source("DemographicFunctions.R")
setwd("../Project3/")

library(boot)
library(forecast)

#***********************************
# Center plot
#***********************************

center.plot(cbind( uva$Kidney[-26], unc$Kidney[-26], mcv$Kidney[-26], duke$Kidney[-26]), Year = seq(1988,2012, 1), title = "Kidney")

##figure for lecture
center.plot(cbind( uva$Kidney[-26],  mcv$Kidney[-26]), Year = seq(1988,2012, 1), title = "Kidney")
plot(uva$Year[-26], uva$Kidney[-26], col = "orange", type = "l", ylim = c(min(uva$Kidney), max(mcv$Kidney)), xlab = "Year", ylab = "No. of Transplants", main = "Kidney Transplants")
lines(mcv$Year[-26], mcv$Kidney[-26], col = "purple")
legend(1990, 120, legend = c("UVA", "MCV"), lwd = 2, col = c("orange", "purple"))

## What do you conclude from this center plot?



#*******************************************
#
#  	Ethnic Diversity Analysis
#
#*******************************************

# Form data sets for the kidney transplants


uvaketh <- subdata("Kidney", uvaeth)

mcvketh <- subdata("Kidney", mcveth)

dukeketh <- subdata("Kidney", dukeeth)



# Remove year 2013 and combine all ethnic groups other than white into one category

# UVA
uvake <- data.frame(uvaketh[-26, "Kidney.W"], Kidney.O = apply(uvaketh[-26,which(colnames(uvaketh) != "Kidney.W")], 1, sum))

# MCV
mcvke <- data.frame(mcvketh[-26, "Kidney.W"], Kidney.O = apply(mcvketh[-26,which(colnames(mcvketh) != "Kidney.W")], 1, sum))

# Duke
dukeke <- data.frame(dukeketh[-26, "Kidney.W"], Kidney.O = apply(dukeketh[-26,which(colnames(dukeketh) != "Kidney.W")], 1, sum))

# UVA Ethnic plot
par(mfrow = c(1,3))
plot(uva$Year[-26], uvake[,1], type = "l", ylim = c(min(uvake), max(uvake)), xlab = "Year", ylab = "No. of Transplants", main = "UVA Transplants by Ethnic Group")
lines(uva$Year[-26], uvake[,2], col = "green")
legend(1990, 70, legend = c("White", "Other"), lwd = 2, col = c("black", "green"))

plot(mcv$Year[-26], mcvke[,1], type = "l", ylim = c(min(mcvke), max(mcvke)), xlab = "Year", ylab = "No. of Transplants", main = "MCV Transplants by Ethnic Group")
lines(mcv$Year[-26], mcvke[,2], col = "green")
legend(1990, 80, legend = c("White", "Other"), lwd = 2, col = c("black", "green"))

plot(duke$Year[-26], dukeke[,1], type = "l", ylim = c(min(dukeke), max(dukeke)), xlab = "Year", ylab = "No. of Transplants", main = "Duke Transplants by Ethnic Group")
lines(duke$Year[-26], dukeke[,2], col = "green")
legend(1990, 60, legend = c("White", "Other"), lwd = 2, col = c("black", "green"))
par(mfrow = c(1,1))


## What do you conclude from these demographic plots?



# Time series plots at the university medical centers
plot(uva$Year[-26], uvake[,1], type = "l", ylim = c(10, 100), col = "orange", main = "Transplants for Whites", ylab = "Percent", xlab = "Year")
lines(uva$Year[-26], mcvke[,1], type = "l", col = "purple")
lines(uva$Year[-26], dukeke[,1], type = "l", col = "blue3")
legend(1990, 100, legend = c("UVA", "MCV", "Duke"), lwd = 2, col = c("orange", "purple", "blue3"))

plot(uva$Year[-26], uvake[,2], type = "l", ylim = c(0, 100), col = "orange", main = "Transplants for Non-Whites", ylab = "Percent", xlab = "Year")
lines(uva$Year[-26], mcvke[,2], type = "l", col = "purple")
lines(uva$Year[-26], dukeke[,2], type = "l", col = "blue3")
legend(1990, 100, legend = c("UVA", "MCV", "Duke"), lwd = 2, col = c("orange", "purple", "blue3"))


## What do you conclude from these time series plots?
```
uva is good at white people , but not good on non-white people
```{r}

# ACF analysis
par(mfrow = c(1,3))
acf(uvake[,2], main = "ACF UVA NW")
acf(mcvke[,2], main = "ACF MCV NW")
acf(dukeke[,2], main = "ACF Duke NW")
par(mfrow = c(1,1))

# PACF analysis
par(mfrow = c(1,3))
pacf(uvake[,2], main = "PACF UVA NW")
pacf(mcvke[,2], main = "PACF MCV NW")
pacf(dukeke[,2], main = "PACF Duke NW")
par(mfrow = c(1,1))

## What do you conclude from the acf and pacf plots?



# Classical tests
t.test(uvake[-26,1], mcvke[-26,1])
t.test(uvake[-26,1], dukeke[-26,1])


t.test(uvake[-26,2], mcvke[-26,2])
t.test(uvake[-26,2], dukeke[-26,2])

## What do you conclude from the t tests?


#******************************************************************
#
#  		Testing the Difference with MCV
#		Boostrapping & Simulation for the Difference
#
#******************************************************************

uvamcv <- uva$Kidney[-26]-mcv$Kidney[-26]

# Plot the difference between uva and mcv
plot(uva$Year[-26], uvamcv, col = "blue", type = "l", xlab = "Time", ylab = "MCV - UVA", main = "Difference between Kidney Transplants at UVA and MCV")
abline(h=0)

# Buidl a linear model uvamcv.lm to predict uvamcv with r11 donor

uvamcv.lm <- lm(uvamcv~r11donor$Kidney[-26])

summary(uvamcv.lm)

# diagnostics

par(mfrow = c(2,2))
plot(uvamcv.lm)
par(mfrow = c(1,1))

# Evaluate correlation of the model residuals
par(mfcol = c(1,2))
acf(uvamcv.lm$residuals)
pacf(uvamcv.lm$residuals)
par(mfcol = c(1,1))

# Buid a time series model of residuals using yule-walker method or mle
uvamcv.ar <- ar(uvamcv.lm$residuals)
uvamcv.ar

# Plot the aic for different numbers of ar terms
plot(uvamcv.ar$aic, type = "h")

##How many ar terms do we need? 


# Adding the time series model
# AR(1)

uvamcv.lm.e1 <- uvamcv.lm$resid[1:24] # new var..1 AR term put resid into AR
uvamcv.lm.eStupid <- uvamcv.lm$resid[1:25] # new var..1 AR term put resid into AR

r11k <- r11donor$Kidney[2:25] # need lag of use 1-24 to pred 2-25

uvamcv <- uva$Kidney[2:25] - mcv$Kidney[2:25] # lag from 1-24 to pred 2-25 diff

uvamcv.dm <- data.frame(uvamcv, r11k, uvamcv.lm.e1)

# Linear model with time series component
uvamcv.lm2<- lm(uvamcv~., data = uvamcv.dm)
summary(uvamcv.lm2)

# diagnostics

par(mfrow = c(2,2))
plot(uvamcv.lm2)
par(mfrow = c(1,1))
# this is $w_t$ may indicate white noise (MA) term

par(mfrow =c(1,2))
acf(uvamcv.lm2$residuals)
pacf(uvamcv.lm2$residuals)
par(mfrow =c(1,1))


##########################
# Forecasting R11 
# We need to forecast the r11 donors and the model residuals.
# Time series model of r11 donors

par(mfrow = c(2,1))
acf(r11donor$Kidney)
pacf(r11donor$Kidney) # AR(1) is good
par(mfrow = c(1,1))

# Time series model of R11 donors.
r11.ar <- ar(r11donor$Kidney[-26])

# Forecast of R11 donors
r11.ar.f <- forecast(r11.ar, h = 1) 

# Creating the new data data fame
uvamcv.nd <- data.frame(r11k = r11.ar.f$mean,uvamcv.lm.e1 = uvamcv.lm.e1[24])
# include r11 forecast and resid term and the use predict

# Predicting the linear model
predict(uvamcv.lm2, newdata = uvamcv.nd, se.fit = T)


# Bootstrap prediction
uvamcv.boot <- RFB(uvamcv.dm, model = uvamcv.lm2, ndata = uvamcv.nd, num = 2000 )

# Bootstrap plot 

plot(uvamcv.boot, index = 1)

##figure diffhist.pdf
plot(uvamcv.boot, index = 1, main = "UVA−MCV Kidey Transplants")


# 2 Sided CI
uvamcv.ci <- boot.ci(uvamcv.boot,index =1)
uvamcv.ci


# Plot of predictions for each value of the pw and the confidence intervals
uvamcv <- uva$Kidney[-26]-mcv$Kidney[-26]

plot( uvamcv[-26]~uva$Year[-26], xlim = c(1988, 2013), type = "l", xlab = "Years", ylab = "No. of Kidney", main = "Predicted Numbers of UVA Kidney Transplants", ylim = c(-80, 50))
points(2013, uvamcv.boot$t0[1], pch = 19)
segments(2013, uvamcv.boot$t0,  2013, uvamcv.ci$percent[4], lty = "dashed" )
segments(2013, uvamcv.boot$t0,  2013, uvamcv.ci$percent[5], lty = "dashed" )
points(2012.5, uva$Kidney[26]-mcv$Kidney[26])
abline(h = 0)
legend(1990,-40, legend = c("Predicted", "Current"), pch = c(19, 1))

#used forecasting for R11

#***************************************************
# 
#  Simulation for Improved CI
#
#***************************************************
# Simulating the results from R11 and the UVA transplant time series

# Get mean and SD for the time series inputs

# Forecast of R11 donors gives 
# parameters for the simulation
r11.ar.f <- predict(r11.ar, se.fit = T) 
r11.ar.f

# Simulating the predictor to obtain CI
uvamcv.sim <- RFBSIM2(uvamcv.dm, model = uvamcv.lm2, ndata = uvamcv.nd, num = 2000, predse = data.frame(r11k = c(1, r11.ar.f$se)) )
plot(uvamcv.sim, index = 1)

##############
# 2 sided CI

uvamcv.sim.ci <- boot.ci(uvamcv.sim, index = 1)

uvamcv.sim.ci

quantile(uvamcv.sim$t, c(.025, .975))

hist(uvamcv.sim$t)

# Plot of difference of UVA and MCV in no. of transplants
uvamcv <- uva$Kidney[-26]-mcv$Kidney[-26]

plot( uvamcv~uva$Year[-26], xlim = c(1988, 2013), type = "l", xlab = "Years", ylab = "No. of Kidney", main = "Predicted Difference Between UVA and MCV Kidney Transplants", ylim = c(uvamcv.sim.ci$percent[4], max(uvamcv[-26])))
#Bootstrapped predictions
points(2013, uvamcv.boot$t0[1], pch = 19)
segments(2013, uvamcv.boot$t0,  2013, uvamcv.ci$percent[4], lty = "dashed" )
segments(2013, uvamcv.boot$t0,  2013, uvamcv.ci$percent[5], lty = "dashed" )
#Simulation predictions
points(2013.5, median(uvamcv.sim$t), pch = 17)
segments(2013.5, median(uvamcv.sim$t),  2013.5, uvamcv.sim.ci$percent[4], lty = "dashed" )
segments(2013.5, median(uvamcv.sim$t),  2013.5, uvamcv.sim.ci$percent[5], lty = "dashed" )
abline(h = 0)
points(2012.5, uva$Kidney[26]-mcv$Kidney[26]) # Current value
legend(1990,-40, legend = c("Bootstrap", "Current", "Simulation"), pch = c(19, 1, 17))
<<<<<<< HEAD:.Rhistory
# setwd("~/Google Drive/UVaGrad/6021/RCode")
# Directory <- dir()
# r.code.files <- Directory[grepl("R$",Directory)]
# files.of.interest <- c("")
# r.code.files <- r.code.files[!grepl("Boot1.R",r.code.files)]
# r.code.files <- r.code.files[!grepl("Boot2.R",r.code.files)]
# r.code.files
# r.code.files[1]
# for (i in 1:length(r.code.files)) {
#   print(r.code.files[i])
#   source(r.code.files[i])
# }
setwd("~/Projects")
setwd("./Project3/TransplantData")
r11.donor<-read.table("R11donor.csv", sep = ",", header = T)
us.donor<-read.table("USdonor.csv", sep = ",", header = T)
#r11.donor$Location <- rep("r11", len.xplant)
#us.donor$Location <- rep("us", len.xplant)
#donor <- merge(r11.donor, us.donor, all.x=TRUE, all.y=TRUE)
#donor$Location <- factor(donor$Location)
len.xplant <- 26
r11.xplant <- read.table("R11xplant.csv", sep = ",", header = T)
uva.xplant <- read.table("UVAxplant.csv", sep = ",", header = T)
duke.xplant <- read.table("Dukexplant.csv", sep = ",", header = T)
mcv.xplant <- read.table("MCVxplant.csv", sep = ",", header = T)
unc.xplant <- read.table("UNCxplant.csv", sep = ",", header = T)
us.xplant <- read.table("UStransplant.csv", sep = ",", header = T)
r11.xplant$Location <- rep("r11", len.xplant)
uva.xplant$Location <- rep("uva", len.xplant)
duke.xplant$Location <- rep("duke", len.xplant)
mcv.xplant$Location <- rep("mcv", len.xplant)
unc.xplant$Location <- rep("unc", len.xplant)
us.xplant$Location <- rep("us", len.xplant)
xplant <- merge(r11.xplant, uva.xplant, all.x=TRUE, all.y=TRUE)
xplant <- merge(xplant, duke.xplant, all.x=TRUE, all.y=TRUE)
xplant <- merge(xplant, mcv.xplant, all.x=TRUE, all.y=TRUE)
xplant <- merge(xplant, unc.xplant, all.x=TRUE, all.y=TRUE)
#xplant <- merge(xplant, us.xplant, all.x=TRUE, all.y=TRUE)
xplant$Location <- factor(xplant$Location)
duke.eth <- read.table('DukeEthnic.csv', sep = ',', header = T)
mcv.eth <- read.table('MCVethnic.csv', sep = ',', header = T)
r11.eth <- read.table('R11ethnic.csv', sep = ',', header = T)
uva.eth <- read.table('UVAethnic.csv', sep = ',', header = T)
uva.eth$Location <- rep("uva", len.xplant)
duke.eth$Location <- rep("duke", len.xplant)
mcv.eth$Location <- rep("mcv", len.xplant)
r11.eth$Location <- rep("r11", len.xplant)
eth <- merge(uva.eth, duke.eth, all.x=TRUE, all.y=TRUE)
eth <- merge(eth, mcv.eth, all.x=TRUE, all.y=TRUE)
eth <- merge(eth, r11.eth, all.x=TRUE, all.y=TRUE)
eth$Location <- factor(eth$Location)
#setwd("~/Google Drive/UVaGrad/6021/RCode/")
setwd("~/Projects")
setwd("./RCode/")
# source("TSbootfunctions.R")
# source("SPM_Panel.R")
# source("Transplant.plots.R")
# source("DemographicFunctions.R")
# source("DemographicFunctions-1.R")
r.code.files <- c("TSbootfunctions.R", "SPM_Panel-1.R", "Transplant.plots.R",
"DemographicFunctions.R", "DemographicFunctions-1.R")
for (i in 1:length(r.code.files)) {
source(r.code.files[i])
}
setwd("~/Projects")
setwd("./Project3/")
uva.xplant <- uva.xplant[-26, c("Year", "Liver", "Liver_DD", "Liver_LD","Kidney", "Kidney_DD", "Kidney_LD")]
mcv.xplant <- mcv.xplant[-26, c("Year","Liver", "Liver_DD", "Liver_LD","Kidney", "Kidney_DD", "Kidney_LD")  ]
duke.xplant <- duke.xplant[-26, c("Year","Liver", "Liver_DD", "Liver_LD","Kidney", "Kidney_DD", "Kidney_LD")]
unc.xplant <- unc.xplant[-26, c("Year","Liver", "Liver_DD", "Liver_LD","Kidney", "Kidney_DD", "Kidney_LD") ]
r11.xplant <- r11.xplant[-26, c("Year","Liver", "Liver_DD", "Liver_LD","Kidney", "Kidney_DD", "Kidney_LD") ]
r11.donor <- r11.donor[-26, c("Year","Liver", "Liver_DD", "Liver_LD","Kidney", "Kidney_DD", "Kidney_LD") ]
bs.mcv.liv.diff<-boot(mcv.liv.diff,bs.mean,R=50000)
uva.kidney<-uva.xplant$Kidney
mcv.kidney<-mcv.xplant$Kidney
duke.kidney<-duke.xplant$Kidney
unc.kidney<-unc.xplant$Kidney
uva.liver<-uva.xplant$Liver
mcv.liver<-mcv.xplant$Liver
duke.liver<-duke.xplant$Liver
unc.liver<-unc.xplant$Liver
mcv.liv.diff <- ts(uva.liver-mcv.liver,1988,2012)
unc.liv.diff <- ts(uva.liver-unc.liver,1988,2012)
duke.liv.diff <- ts(uva.liver-duke.liver,1988,2012)
mcv.kid.diff <- ts(uva.kidney-mcv.kidney,1988,2012)
unc.kid.diff <- ts(uva.kidney-unc.kidney,1988,2012)
duke.kid.diff <- ts(uva.kidney-unc.kidney,1988,2012)
bs.mcv.liv.diff<-boot(mcv.liv.diff,bs.mean,R=50000)
bs.unc.liv.diff<-boot(unc.liv.diff,bs.mean,R=50000)
bs.duke.liv.diff<-boot(duke.liv.diff,bs.mean,R=50000)
bs.mean<-function(x,i)
{
return(mean(x[i]))
}
bs.mcv.liv.diff<-boot(mcv.liv.diff,bs.mean,R=50000)
bs.unc.liv.diff<-boot(unc.liv.diff,bs.mean,R=50000)
bs.duke.liv.diff<-boot(duke.liv.diff,bs.mean,R=50000)
bs.mcv.kid.diff<-boot(mcv.kid.diff,bs.mean,R=50000)
bs.unc.kid.diff<-boot(unc.kid.diff,bs.mean,R=50000)
bs.duke.kid.diff<-boot(duke.kid.diff,bs.mean,R=50000)
plot(bs.mcv.liv.diff,index=1, main="Bootstrapped Mean Difference UVa and MCV")
plot(bs.unc.liv.diff,index=1)
plot(bs.duke.liv.diff,index=1)
plot(bs.mcv.kid.diff,index=1)
plot(bs.unc.kid.diff,index=1)
plot(bs.duke.kid.diff,index=1)
boot.ci(bs.mcv.liv.diff,0.95,type=c('bca','perc'))
boot.ci(bs.unc.liv.diff,0.95,type=c('bca','perc'))
boot.ci(bs.duke.liv.diff,0.95,type=c('bca','perc'))
boot.ci(bs.mcv.kid.diff,0.95,type=c('bca','perc'))
boot.ci(bs.unc.kid.diff,0.95,type=c('bca','perc'))
boot.ci(bs.duke.kid.diff,0.95,type=c('bca','perc'))
bs.mcv.liv.diff.100k<-boot(mcv.liv.diff,bs.mean,R=100000)
bs.unc.liv.diff.100k<-boot(unc.liv.diff,bs.mean,R=100000)
bs.duke.liv.diff.100k<-boot(duke.liv.diff,bs.mean,R=100000)
bs.mcv.kid.diff.100k<-boot(mcv.kid.diff,bs.mean,R=100000)
bs.unc.kid.diff.100k<-boot(unc.kid.diff,bs.mean,R=100000)
bs.duke.kid.diff.100k<-boot(duke.kid.diff,bs.mean,R=100000)
boot.ci(bs.mcv.liv.diff.100k,0.95,type=c('bca','perc'))
boot.ci(bs.unc.liv.diff.100k,0.95,type=c('bca','perc'))
boot.ci(bs.duke.liv.diff.100k,0.95,type=c('bca','perc'))
boot.ci(bs.mcv.kid.diff.100k,0.95,type=c('bca','perc'))
boot.ci(bs.unc.kid.diff.100k,0.95,type=c('bca','perc'))
boot.ci(bs.duke.kid.diff.100k,0.95,type=c('bca','perc'))
plot(bs.duke.kid.diff.100k,index=1)
plot(bs.duke.kid.diff.100k,index=1)
bs.mcv.liv.diff.100k
bs.unc.liv.diff.100k
bs.duke.liv.diff.100k
bs.mcv.kid.diff.100k
bs.unc.kid.diff.100k
bs.duke.kid.diff.100k
duke.kid.diff <- ts(uva.kidney-duke.kidney,1988,2012)
setwd("~/Box Documents/")
png("./project/figures/diff_kidney.png", width=900, height=900)#, pointsize=30)
par(mfrow=c(3,1), ps=20)
ts.plot(mcv.kid.diff,ylab='UVa-MCV',
main = "Difference in Number of Kidney Transplants, UVA-MCV")
abline(0,0,lty=3)
ts.plot(unc.kid.diff,ylab='UVa-UNC',
main = "Difference in Number of Kidney Transplants, UVA-UNC")
abline(0,0,lty=3)
ts.plot(duke.kid.diff,ylab='UVa-Duke',
main = "Difference in Number of Kidney Transplants, UVA-Duke")
abline(0,0,lty=3)
par(mfrow=c(1,1), ps=20)
dev.off()
bs.duke.liv.diff.100k<-boot(duke.liv.diff,bs.mean,R=100000)
bs.duke.liv.diff
png("./project/figures/boot_duke_kidney.png", width=700, height=900)#, pointsize=30)
plot(bs.duke.kid.diff.100k,index=1)
dev.off()
par(mfrow=c(1,1), ps=20)
boot.ci(bs.duke.kid.diff.100k,0.95,type=c('bca','perc'))
bs.duke.kid.diff.100k<-boot(duke.kid.diff,bs.mean,R=100000)
bs.duke.kid.diff.100k
png("./project/figures/boot_duke_kidney.png", width=700, height=900)#, pointsize=30)
plot(bs.duke.kid.diff.100k,index=1)
dev.off()
par(mfrow=c(1,1), ps=20)
boot.ci(bs.duke.kid.diff.100k,0.95,type=c('bca','perc'))
par(mfrow=c(1,1), ps=20)
png("./project/figures/boot_mcv_liver.png", width=700, height=900)#, pointsize=30)
plot(bs.mcv.liv.diff.100k,index=1, main="Bootstrapped Mean Difference UVa and MCV")
dev.off()
png("./project/figures/boot_unc_liver.png", width=700, height=900)#, pointsize=30)
plot(bs.unc.liv.diff.100k,index=1)
dev.off()
png("./project/figures/boot_duke_liver.png", width=700, height=900)#, pointsize=30)
plot(bs.duke.liv.diff.100k,index=1)
dev.off()
png("./project/figures/boot_mcv_kidney.png", width=700, height=900)#, pointsize=30)
plot(bs.mcv.kid.diff.100k,index=1)
dev.off()
png("./project/figures/boot_unc_kidney.png", width=700, height=900)#, pointsize=30)
plot(bs.unc.kid.diff.100k,index=1)
dev.off()
png("./project/figures/boot_duke_kidney.png", width=700, height=900)#, pointsize=30)
plot(bs.duke.kid.diff.100k,index=1)
dev.off()
uva.kid.lm <- lm(uva.xplant$Kidney ~ r11.donor$Kidney)
summary(uva.kid.lm)
par(mfrow=c(2,2), ps=20)
plot(uva.kid.lm)
par(mfrow=c(1,1))
uva.liv.lm <- lm(uva.xplant$Liver ~ r11.donor$Liver)
summary(uva.liv.lm)
par(mfrow=c(2,2), ps=20)
png("./project/figures/diag_liv_uva-r11.png", width=900, height=900)#, pointsize=30)
plot(uva.liv.lm)
dev.off()
par(mfrow=c(1,1))
par(mfrow=c(2,2), ps=20)
png("./project/figures/diag_kid_uva-r11.png", width=900, height=900)#, pointsize=30)
plot(uva.kid.lm)
dev.off()
par(mfrow=c(1,1))
png("./project/figures/diag_liv_uva-r11.png", width=900, height=900)#, pointsize=30)
par(mfrow=c(2,2), ps=20)
plot(uva.liv.lm)
dev.off()
par(mfrow=c(1,1))
png("./project/figures/diag_kid_uva-r11.png", width=900, height=900)#, pointsize=30)
par(mfrow=c(2,2), ps=20)
plot(uva.kid.lm)
par(mfrow=c(1,1))
dev.off()
uva.lfit <- fitted(uva.liv.lm)
uva.kfit <- fitted(uva.kid.lm)
=======
# are the ranges close to 0??? including ConfInt? the 
# subdata functions??? 
```
>>>>>>> 4c7004708f93f7e8be14ed11cdbb0b906e0e1ba7:L6_25Nov13/XplantKidney.Rmd
